services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    profiles: ["production"]

  backend:
    build: ./backend
    container_name: telegram-music-api
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: telegram-music-frontend
    depends_on:
      - backend
    networks:
      - app-network

  bot:
    build: ./bot
    container_name: telegram-music-bot
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:17
    container_name: telegram-music-db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
