services:
  nginx:
    volumes:
      - frontend_dist:/var/www/frontend
  backend:
    build:
      target: prod

  frontend:
    build:
      target: build
    volumes:
      - frontend_dist:/app/dist
  bot:
    build:
      target: prod

volumes:
  frontend_dist
