"""Delete content from posts table and make it pivot on links only

Revision ID: e2f8d61d66d9
Revises: cc3c826f6f21
Create Date: 2026-08-15 09:45:42.997380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f8d61d66d9'
down_revision: Union[str, Sequence[str], None] = 'cc3c826f6f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('vendor', postgresql.ENUM('spotify', 'yandex', 'vk', name='track_vendor'), nullable=False))
    op.add_column('posts', sa.Column('link', sa.String(length=255), nullable=False))
    op.drop_column('posts', 'type')
    op.drop_column('posts', 'content_type')
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.VARCHAR(length=600), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('content_type', postgresql.ENUM('direct_link', 'iframe', name='content_type'), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('type', postgresql.ENUM('spotify', 'yandex', 'vk', name='track_vendor'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'link')
    op.drop_column('posts', 'vendor')
    # ### end Alembic commands ###
